<h3>MeetNotes Automation Testcase Summary</h3><b>Start Time: </b>2017-07-27 15:31:46.472000<br><b>End Time:  </b>2017-07-27 15:32:09.406000<br><b>Duration: </b>0:00:22.934000<br><b>Status: </b> Pass 0 Failure 0 Error 1<br><br><table border=1 cellspacing=0 cellpadding=0><tr bgcolor=#C0C0C0><th align='left' style='padding: 5px 5px 5px 5px;'>Test Group/Test case</th><th style='padding: 5px 5px 5px 5px;'>Count</th><th style='padding: 5px 5px 5px 5px;'>Pass</th><th style='padding: 5px 5px 5px 5px;'>Fail</th><th style='padding: 5px 5px 5px 5px;'>Error</th><th style='padding: 5px 5px 5px 5px;'>Execution Time</th></tr><tr bgcolor=#FF0000><td> tests.test_add_item_and_verify.TestCases </td><td align='center'>1</td><td align='center'>0</td><td align='center'>0</td><td align='center'>1</td><td align='center'>22.934</tr><tr><td style='color:brown;'><ul><li>test_search_and_add_item_and_verify_in_cart</td><td align='center' style='overflow-y:scroll' colspan='4'><div style='color:brown;'> error </div><div style='width: 500px; height: 100px'>
Traceback (most recent call last):
  File "C:\Users\Joydeep\flipkart-automation\tests\test_add_item_and_verify.py", line 15, in test_search_and_add_item_and_verify_in_cart
    self.assertEquals(current_page.get_greet_user_text(GREET_USER_TEXT), "No")
AssertionError: 'Yes' != 'No'
		</div></td><td align='center'>22.934</td></tr><tr><th>Total</th><th align='center'>1</th><th align='center'>0</th><th align='center'>0</th><th align='center'>1</th><th>22.934</tr></table></table>